name: Deploy to AKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image to ACR
      run: |
        docker build -t aksacrpoctest.azurecr.io/hello-world:${{ github.run_number }} .
        echo ${{ secrets.ACR_PASSWORD }} | docker login aksacrpoctest.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker push aksacrpoctest.azurecr.io/hello-world:${{ github.run_number }}

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group aks-poc-rg --name aks-poc-cluster --overwrite-existing
        sed -i "s|mcr.microsoft.com/azuredocs/aks-helloworld:v1|aksacrpoctest.azurecr.io/hello-world:${{ github.run_number }}|g" app.yaml
        kubectl apply -f app.yaml
